import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["200", "400", "600"], subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "ChatEasy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative min-h-screen bg-[url('/bg2.jpg')] flex items-center justify-center h-[100vh] text-white
`}>
        <div className="relative z-10 min-h-screen ">{children}</div>
      </body>
    </html>
  );
}